### PR TITLE
Adding segment/vertex snapping options to the shape editor

### PR DESCRIPTION
**Pull request by mathijs-dumon**
Should be merge only if the corresponding PR from MapWinGIS has been accepted (https://github.com/MapWindow/MapWinGIS/pull/132)

### CODE REVIEW

**Comment by mathijs-dumon** [comment]
@pmeems Is there anything I still need to do for this?

**Comment by pmeems** [comment]
@mathijs-dumon Did you verify it is still working as expected with the latest dev code of MapWinGIS.
If so I will merge your changes.

**Comment by pmeems** [comment]
@mathijs-dumon I did a review of your pull request and it has many more changes and improvements than just 'Adding segment/vertex snapping options to the shape editor'.
That is fine but to track changes I want to ask you if you can make a list of your changes so I can add it to our issue tracker and then it will end up in the release notes.

**Comment by mathijs-dumon** [comment]
Ah shoot, I actually wanted to make seperate pull requests for these. Didn't realize this pr was on the develop branch. My bad.
I'll do as you suggest and document the changes with the relevant commits asap.

**Comment by mathijs-dumon** [comment]
closing as this is no longer relevant

**Pull request closed without merging**
